[project]
name = "stroke-risk-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "notebook>=7.3.3",
    "pandas>=2.0.3",
    "scikit-learn>=1.3.2",
    "xgboost>=2.1.4",
]
